### ISSUE TITLE
DIFFERENT CDS HITS

### ISSUE THREAD

**Issue by vappiah** [ncbi/pgap#107]
I wanted to check the consistency of pgap. So I downloaded the fasta file for M. ulcerans Agy99 (Available [here ](https://www.ncbi.nlm.nih.gov/nuccore/CP000325.1))
Below are what I found out

[pgap_output.pdf](https://github.com/ncbi/pgap/files/5424491/pgap_output.pdf)

Below are some questions and comments

1. IS2606 is in the family IS256  so could there be a reason why some IS are explicitly labeled IS2606 and others IS256. 

2. pgap returned ISAs1 so it is not possible to know which of these IS were IS2404 or ISMul1. [ ISFinder](https://www-is.biotoul.fr/blast.php)  returned the hits stating the type of IS and the family and in the Agy99.fasta it returned IS2606, ISMul1 and IS2404. See below for a snap shot
![ISFINDER](https://user-images.githubusercontent.com/14283733/96908530-4d500980-148c-11eb-8ee1-d733b8c2bdc2.png)

Is it possible for pgap to explicitly state which IS it identifies? or I have to manually blast to check ?

I would be happy if these comments are addressed so that I can confidently use pgap to annotate my sequence data which is also M. ulcerans.

Below are my input and submol yaml files and the Agy99 fasta file I used ( I added .txt because github does not allow me to upload with their original extensions).

[input.yaml.txt](https://github.com/ncbi/pgap/files/5424592/input.yaml.txt)
[submol.yaml.txt](https://github.com/ncbi/pgap/files/5424593/submol.yaml.txt)

[Agy99.fasta.txt](https://github.com/ncbi/pgap/files/5424596/Agy99.fasta.txt)

Below are the gene bank files  I used. The original and and pgap generated file
[Agy99.gbk.txt](https://github.com/ncbi/pgap/files/5425038/Agy99.gbk.txt)
[Agy99_pgap.gbk.txt](https://github.com/ncbi/pgap/files/5425039/Agy99_pgap.gbk.txt)

Here is the python script I used to check
[check.py.txt](https://github.com/ncbi/pgap/files/5425030/check.py.txt)

**Comment by thibaudnis** [comment]
@jotes35 : we assigned the question to a curator and will get back to you as soon as we can. Thanks!

**Comment by jotes35** [comment]
Thanks @thibaudnis  I will be waiting

**Comment by liw13** [comment]
We primarily use two types of evidence to assign names to transposase. A BlastRule evidence was built from a specific transposase, which has a unique name and family assignment in IS Finder. We use 99% identity and 95% coverage as BlastRule cutoffs. If a protein is hit by a BlastRule above this cutoff based on BLASTp search, it will get the name from the BlastRule. We also use HMMs built from a larger number of transposases of the same IS family to annotate transposases. So, the HMM name is broader than the BlastRule name, but has lower precedence in protein naming. If a protein is hit by both an HMM and a BlastRule, it will be named by the BlastRule. If a protein is hit by only an HMM, it will be named by the HMM. 
To answer your questions:
1. IS2606 is in the family IS256 so could there be a reason why some IS are explicitly labeled IS2606 and others IS256.
You are right. The IS2606 tranposase has a more specific name because it’s hit by the BlastRule NBR004064 (IS256-like element IS2606 family transposase) above the cutoffs. Other IS256 transposases don’t have specific names because they are not hit by BlastRule NBR004064 but hit by the HMM NF033543 (IS256 family transposase).
2. pgap returned ISAs1 so it is not possible to know which of these IS were IS2404 or ISMul1. ISFinder returned the hits stating the type of IS and the family and in the Agy99.fasta it returned IS2606, ISMul1 and IS2404. 
Based on our evidence and cutoffs, the ISAs1 family transposases in strain Agy99 genome can only be annotated based HMM NF033564 (ISAs1 family transposase). Some of them may be hit by a specific BlastRule evidence but the identity and/or coverage do not meet the BlastRule cutoffs. Therefore, they are not named with more specific names (such as ISMul1,IS2404, ISAzo3, ISAzo8 etc.).

**Comment by jotes35** [comment]
Thanks for the clarification @liw13

**Comment by jotes35** [comment]
@liw13 is there any option to define your own cutoff in pgap? 

I am saying this because we sequenced an M. ulcerans  genome and used pgap to annotate and had a similar observation with respect to the naming of the IS sequence ( family names instead of specific IS). But we believe our sequence has specific IS present. Please advice.   
PS. We used oxford MINION to do the sequencing

**Comment by thibaudnis** [comment]
Our goal is to keep the docker version of PGAP the same as the code used at NCBI. If you wish to make changes to parameters or input data, you will need to take it upon yourself. What do you intend to do with the annotation you produce? You are free to modify the names in the annotation produced by PGAP. If you submitted these edited files to GenBank, a comment will be added to the records explaining that the annotation was modified after PGAP ran.

**Comment by ncbiwenjunli** [comment]
You can contact IS Finder to discuss whether they are new transposases. Usually, IS Finder assign specific names to new insertion sequences and related transposases. You can email me if they are new IS/transposases. I would be happy to build new evidence for them. Thanks!
