### ISSUE TITLE
Annotating with a custom genebank file

### ISSUE THREAD

**Issue by jotes35** [ncbi/pgap#109]
Hi pgap developers, I would like to know if its possible to annotate a sequence using a dowloaded genebank file instead of the pgap default database?

**Comment by thibaudnis** [comment]
Hello! You can run PGAP on the assembled sequence of any genome from a bacterial or archaeal isolate. The genome can be closed or not, although the less fragmented, the better the results are likely to be. Make sure to review how to prepare the inputs at https://github.com/ncbi/pgap/wiki/Input-Files.

**Comment by jotes35** [comment]
Hi @thibaudnis  what I mean is if lets say you have a fasta file A that you want to annotate . Can you use information from lets say a reference genome B to annotate? For example I have an M. ulcerans sequence data, can I specify in pgap to use the reference genome genebank as the database from which my file will be annotated?

**Comment by azat-badretdin** [comment]
> Can you use information from lets say a reference genome B to annotate? 

<not Françoise here> 

No, you can't.
 
Projecting genomic information from a close genome is a very attractive and obvious idea, but there are treacherous underwater details that are likely to derail such a project because of alignment-related problems and, most importantly, inevitable mess (whether artificial, say, sequencing errors, or biological, transposon bombing, for example) in genomic sequences: both reference and targets. This idea have been discussed here since long time ago and current position is that we are not doing that in the nearest future. 

Françoise knows better about problems with genomic projecting, she might be able to add more to this (or correct me).

**Comment by thibaudnis** [comment]
Thanks for clarifying the question. PGAP is a de novo annotation pipeline. It doesn't annotate by projection.

**Comment by jotes35** [comment]
Thanks very much for the clarification @azat-badretdin  and @thibaudnis

**Comment by jotes35** [comment]
@azat-badretdin @thibaudnis .

I made another I asked another question [here](https://github.com/ncbi/pgap/issues/109#event-3931029156)

**Comment by azat-badretdin** [comment]
The link goes to this page.
