### ISSUE TITLE
[FEATURE REQUEST] distributing CWLs on dockstore

### ISSUE THREAD

**Issue by dpark01** [ncbi/pgap#117]
Hi folks, it's awesome that PGAP is available in a set of containerized CWL workflows. I was just watching Francoise's talk at ASM NGS this morning.

**Is your feature request related to a problem? Please describe.**
It appears that the preferred method of pulling these CWLs is either via cwltool or downloading from github. I think it's worth considering going one step further and distributing the CWLs on [Dockstore](https://dockstore.org/).

**Describe the solution you'd like**
It would be great if the key CWL workflows in this repo were distributed on Dockstore. The most straightforward way to do this is using their [automated github integrations](https://docs.dockstore.org/en/develop/getting-started/github-apps/github-apps-landing-page.html).

This basically involves 1) setting up your accounts on dockstore, perhaps even an "NCBI" Organization, 2) setting up a Github Action on this repo, 3) adding a .dockstore.yml on this repo that describes the workflows you want to highlight, along with any descriptions, test input data, etc.

This would enable automated integration for users with a number of genomic cloud compute platforms that can operate on CWLs (such as DNAnexus or Seven Bridges).

**Describe alternatives you've considered**
Any other workflow distribution mechanism that complies with the [GA4GH Tool Registry Service API](https://ga4gh.github.io/tool-registry-service-schemas/) such as biocontainers.

**Additional context**
Related, but selfish plug for my ASM NGS [poster](https://github.com/asmngs/asmngs20/blob/master/posters/Park_D-2020.12.08-ASM_NGS-poster-dpark.pdf) (and [read through](https://github.com/asmngs/asmngs20/blob/master/posters/Park_D-2020.12.08-ASM-NGS-poster-narrative.pdf)), which motivates why you might want to do this.

**Comment by thibaudnis** [comment]
Hi! Thanks for joining the ASM-NGS session! There are a couple of impediments to publishing on Dockstore: 1) our CWL only works with cwltool, due to CWL spec compliance issues with other runners, 2) we assume the large reference data is available on the host, which we require as input to the CWL. Given those 2 issues, doing the work to put PGAP into Dockstore, would not give the desired benefit of being able to use it the way it is intended.
That said, once we can modify our CWL code to work well in other runners, putting it up in Dockstore is a natural follow-up activity, for publishing the workflow.
