### ISSUE TITLE
Annotating different chromosomes for the same organism

### ISSUE THREAD

**Issue by vappiah** [ncbi/pgap#122]
Hello PGAP developers. @thibaudnis @azat-badretdin  Thanks for support. I have vibro cholerae genomes that i am annotating. From the wiki, I can specify the region using the location . However vibro cholerae has two chromosomes ( 1 and 2) . Is there a way to be specific which chromosome number to use in PGAP? or I use the generic _chromosome_ ? Thanks

**Comment by thibaudnis** [comment]
Hi Vincent, yes, you can do this. Please add `[location=chromosome] [chromosome=1] ` and `[location=chromosome] [chromosome=2] ` after the seqids, in the definition lines for chr 1 and chr 2 respectively in the input FASTA.

**Comment by vappiah** [comment]
> `` after the seqids, in the definition lines for chr 1 and chr 2 respectively in the input FASTA.

Hi @thibaudnis Thanks for the response. Kindly confirm if the configuration I have below is correct
Genome-assembly-fasta
![genome-assembly-fasta](https://user-images.githubusercontent.com/14283733/107212069-54c8fd80-69fe-11eb-8f42-f37f068757cf.png)
Generic.yaml
![generic-yaml](https://user-images.githubusercontent.com/14283733/107212204-817d1500-69fe-11eb-99d8-9c7177e5931e.png)
Submol.yam
![submol](https://user-images.githubusercontent.com/14283733/107212246-92c62180-69fe-11eb-949a-7e6608f60b75.png)

**Comment by azat-badretdin** [comment]
Technically, using "location" both in FASTA and submol file is redundant here. Specifying "location" in FASTA file, being more specific (it applies only to one sequence), overwrites the "location" in submol.file (more generic - applies to the whole set of sequences). 

>  vibro cholerae has two chromosomes ( 1 and 2) 

Since you have only these two in the input, specifying location="chromosome" in the submol file should be enough. 

BTW, execution must be noticeably faster now: we switched recently to using order-specific and, thus, much smaller reference BLAST databases for chromosomes (plasmids are still annotated using full set of reference proteins).

**Comment by vappiah** [comment]
Hi @azat-badretdin . The two chromosomes are in different files so that means i just have to specify location='chromosome' and I should be fine?

**Comment by azat-badretdin** [comment]
> so that means i just have to specify location='chromosome' 

Yes, you can specify it in submol (which means "apply to ALL molecules") or in FASTA file in headers for _both_ chromosomes. Specifying it in both files is redundant. 

You are already fine with your current setup. I was just mentioning the redundancy

**Comment by vappiah** [comment]
Thanks very much @azat-badretdin .
