### ISSUE TITLE
ent2sqn: could not find correct authors or cit-sub, resetting obligatory fields of submit-block with empty values

### ISSUE THREAD

**Issue by anilchauhanhp9** [ncbi/pgap#144]
Hi, i ran the tool on my own assembly using command:
**python /home/hamlab/PGAP/pgap.py -D /usr/local/bin/singularity -r --taxcheck --debug --cpus 10  -m k --ignore-all-errors -o /media/hamlab/c191ebf9-60f8-475d-8435-8193920ec7ed/Srijana/nanopore_data/Sri_whole_genome_sikkim_25032021/analysis/Error_correction/after_QC_trimming/canu/medaka_barcode11/PGAP_result /media/hamlab/c191ebf9-60f8-475d-8435-8193920ec7ed/Srijana/nanopore_data/Sri_whole_genome_sikkim_25032021/analysis/Error_correction/after_QC_trimming/canu/medaka_barcode11/barcode11.yaml**
The tool gave the following error
 WARNING Final process status is permanentFail
The log and xml files are attached
[cwltool.log.gz](https://github.com/ncbi/pgap/files/6434530/cwltool.log.gz)
[initial_asndisc_diag.xml.gz](https://github.com/ncbi/pgap/files/6434531/initial_asndisc_diag.xml.gz)
[initial_asnval_diag.xml.gz](https://github.com/ncbi/pgap/files/6434532/initial_asnval_diag.xml.gz)
Please help

**Comment by azat-badretdin** [comment]
Could you please post your input `submol.yaml` file?

**Comment by azat-badretdin** [comment]
There are two issues here: first, it looks like we have a loophole in our `submol.yaml` input processing that allows empty values. We should be treating them as missing instead. 

Second, practical issue, is that in order to elucidate potential user input problems, I would suggest that you modify your input, `submol.yaml` yourself for now, to exclude all empty fields, adding them later on as needed, based on the reaction of the software.

Could you please do that?

Thanks

**Comment by anilchauhanhp9** [comment]
Hi,
the tool is working fine now
Thank you for the help
