### ISSUE TITLE
Will any information be uploaded to NCBI?

### ISSUE THREAD

**Issue by Buuntu** [ncbi/pgap#22]
For privacy and IP reasons, I was wondering if any information was uploaded to NCBI when running locally with the `-n` flag?  I am working with private genomes.

**Comment by slottad** [comment]
Not intentionally. Unfortunately, some of the steps in this pipeline still access NCBI CGI services, even though they don't actually need to. This is because they are the same programs we use internally, and sometimes programmers take shortcuts. Shocking I know. While we are working to correct this, it will not be a quick process.

In the meantime, I can assure you that in no case is your sequence ever sent to us by this pipeline. We only want it as part of a formal submission process where you agree to eventually release it publically. One of the main use cases that inspired the creation of this pipeline was to allow users, such as yourself, to use our annotation resources without giving away their private data.
