### ISSUE TITLE
[FEATURE REQUEST] Custom database for annotation

### ISSUE THREAD

**Issue by zinque** [ncbi/pgap#263]
Dear PGAP,
Are there any plans to implement a feature to enable users to also provide a custom sequence database for annotation purposes? (equivalent to the --proteins option in prokka)
Alternatively, do you have a suggestion how/where in the PGAP pipeline one could implement a custom sequence database?
Apologies if this request has been raised previously, although I couldn't find it.

**Comment by azat-badretdin** [comment]
Thank you for your report, user @zinque 

Right now there is no easy way to plug in difference reference data since information about specific reference entries (proteins, for example) is distributed among several files. 

> do you have a suggestion how/where in the PGAP pipeline one could implement a custom sequence database?

It is possible to swap it right now and we have weekly updates for internal usage. I am not sure what would be our LOE to do that? 

But it's an interesting question.

**Comment by zinque** [comment]
> It is possible to swap it right now and we have weekly updates for internal usage. I am not sure what would be our LOE to do that? 
> 

I don't know if the question was addressed to me or internally, but we could be willing to spend some effort in integrating a custom database.

**Comment by azat-badretdin** [comment]
Internally. My apologies for confusion.

We will discuss it internally at the earliest opportunity (summer is traditionally slower than other seasons because of vacations). Thank you for your request!
