### ISSUE TITLE
run failed

### ISSUE THREAD

**Issue by Mayankguptai** [ncbi/pgap#34]
Hey 

I am working with some bacterial genome but I am getting following msg.

`grep -i "fail" cwltool.log`
WARNING [job pgapx_yaml_ctl] completed permanentFail
WARNING [step pgapx_yaml_ctl] completed permanentFail
INFO [workflow prepare_input_template] completed permanentFail
WARNING [step prepare_input_template] completed permanentFail
INFO [workflow ] completed permanentFail
WARNING Final process status is permanentFail

Other details are-
` grep -P '2019.*\[.*\].*\$' cwltool.log | tail`
[2019-08-27 12:56:43] INFO [job blastn_wnode] /pgap/output/debug/tmp-outdir/qb9iws6x$ blastn_wnode \
[2019-08-27 12:56:50] INFO [job gpx_make_outputs] /pgap/output/debug/tmp-outdir/mydkuqrv$ gpx_make_outputs \
[2019-08-27 12:56:50] INFO [job Find_Frequent_contam_in_prok_Hits] /pgap/output/debug/tmp-outdir/9z342mhf$ align_find_frequent \
[2019-08-27 12:56:51] INFO [job Filter_contam_in_prok_BLAST_Results] /pgap/output/debug/tmp-outdir/m82o2kgc$ align_filter \
[2019-08-27 12:56:54] INFO [job Generate_contam_in_prok_hit_features] /pgap/output/debug/tmp-outdir/yy84irh6$ generate_fscr_feats \
[2019-08-27 12:56:58] INFO [job fscr_calls_pass1] /pgap/output/debug/tmp-outdir/p7y20jeh$ fscr_calls_pass1 \
[2019-08-27 12:57:01] INFO [job fscr_format_calls] /pgap/output/debug/tmp-outdir/orbedbxc$ fscr_format_calls \
[2019-08-27 12:57:07] INFO [job screen_evaluate] /pgap/output/debug/tmp-outdir/mpq331kb$ screen_evaluate \
[2019-08-27 12:57:07] INFO [job yaml2json] /pgap/output/debug/tmp-outdir/7yg5pgqn$ yaml2json.py \
[2019-08-27 12:57:08] INFO [job pgapx_yaml_ctl] /pgap/output/debug/tmp-outdir/gk938743$ pgapx_yaml_ctl \

Thanks 
Mayank

**Comment by azat-badretdin** [comment]
Apologies for belated reply. 

Could you please post the part of `cwltool.log` between ```[2019-08-27 12:57:08] INFO [job pgapx_yaml_ctl] /pgap/output/debug/tmp-outdir/gk938743$ pgapx_yaml_ctl \``` and next boilerplate (`'2019.*\[.*\].*\$' `)?

**Comment by Mayankguptai** [comment]
Yeah sure. Attaching cwltool.log file for this run.
[cwltool.log](https://github.com/ncbi/pgap/files/3579658/cwltool.log)

**Comment by azat-badretdin** [comment]
Thanks. Could you please check if you can `find . pgapx_yaml_ctl.\*log` and `find . submol.yaml`? And post them?

**Comment by Mayankguptai** [comment]
Yeah sure. I guess you are looking for pgapx_yaml_ctl log file and submol.yaml file. Attaching these files.
[pgapx_yaml_ctl.1000.log](https://github.com/ncbi/pgap/files/3582682/pgapx_yaml_ctl.1000.log)

[submol.txt](https://github.com/ncbi/pgap/files/3582703/submol.txt)

**Comment by azat-badretdin** [comment]
>pgapx_yaml_ctl.1000.log

... contains the answer: `Unknown organism Oscillatoria formosa`

The search for it in our **NCBI Taxonomy database** leads us further down the rabbit hole: this name actually resolves into [_Kamptonema formosum_](https://www.ncbi.nlm.nih.gov/Taxonomy/Browser/wwwtax.cgi?mode=Info&id=331992&lvl=3&lin=f&keep=1&srchmode=1&unlock) with a homotypic synonym _Oscillatoria formosa_ 

Due to requirements of running in isolation PGAPX is using a snapshot of NCBI Taxonomy relevant to our processing, and it is, therefore, limited to necessities only due to volume constraints and somewhat idiosyncratic nature of snapshot production. 

I personally think that adding synonym indexing to our snapshot could be a good idea

I will open internal discussion on the subject of supporting synonym indexing in our taxonomy processing. 

I will leave this ticket open as a feature request.

For your goals, the workaround is to use the superofficial species name _Kamptonema formosum_ instead of _Oscillatoria formosa_

Please let us know how it worked.

Thanks for your valuable discovery!

**Comment by Mayankguptai** [comment]
Okay thanks, I will try to run it again by changing species name.

However, I have one query about those species name which are not present in NCBI Taxonomy database, how can I proceed with them?

**Comment by azat-badretdin** [comment]
For the actual results, you are safe to choose any other species from the same genus, I think. 

In case you want this to be submitted to Genbank then the process is to request a new taxonomic node from our NCBI Taxonomy.

**Comment by Mayankguptai** [comment]
@azat-badretdin, how to cite PGAP in publications?

**Comment by azat-badretdin** [comment]
Thank you for your question! I addressed it to the members of our team who are more knowledgeable about this issue.

**Comment by thibaudnis** [comment]
Hi, please cite the latest PGAP publication: https://www.ncbi.nlm.nih.gov/pubmed/29112715. Thanks you!

**Comment by Mayankguptai** [comment]
Ok, thanks.
