### ISSUE TITLE
Execute_CRISPR_wnode failed

### ISSUE THREAD

**Issue by liubovch** [ncbi/pgap#42]
Hi,

I am trying to annotate some short region from a bacterial genome. It is around 30 kb. I ran the program like this:
```
./pgap.py --ignore-all-errors -r -v -d -o pgap_annotation XXXXX_input.yaml
```
I am getting the following error message:

```
[2019-10-21 12:10:54] INFO [job Execute_CRISPR_submit] Max memory used: 36MiB
[2019-10-21 12:10:54] INFO [job Execute_CRISPR_submit] completed success
[2019-10-21 12:10:54] INFO [step Execute_CRISPR_submit] completed success
[2019-10-21 12:10:54] INFO [workflow bacterial_mobile_elem] starting step Execute_CRISPR_wnode
[2019-10-21 12:10:54] INFO [step Execute_CRISPR_wnode] start
[2019-10-21 12:10:54] INFO [job Execute_CRISPR_wnode] /pgap/output/debug/tmp-outdir/2ikx9n0a$ ncbi_crisper_wnode \
    -asn-cache \
    /tmp/tmpnj6oc9ec/stg02a16832-2d47-46e4-8c77-4d21008e0525/sequence_cache \
    -ncbi-crisper-path \
    /opt/crispr/1.0/bin/ \
    -input-jobs \
    /tmp/tmpnj6oc9ec/stg1e9332d9-e2d5-4c4b-9fb8-e45740ccfe8b/jobs.xml \
    -O \
    output
00324/000/0000/P  320D0144DADA04E1 0006/0006 2019-10-21T12:10:56.528834 a89a6049184f    UNK_CLIENT      320D0144DADA04E1_0000SID ncbi_crisper_wnode Info: LIB "wn_app.cpp", line 273: ncbi::CGPX_WorkerApp::Run() --- output path: /pgap/output/debug/tmp-outdir/2ikx9n0a/output
=== STDOUT: /opt/crispr/1.0/bin//pilercr -in /tmp/tmpn15i4az6/ncbi_crisper_wnode.324.324120404883200QhQlm/fasta_by_scaffold.324.32431717638912PgANHV/0.fa  -out .331.0.fa.pilecr.tmp -noinfo
FATAL: /opt/crispr/1.0/bin//pilercr -in /tmp/tmpn15i4az6/ncbi_crisper_wnode.324.324120404883200QhQlm/fasta_by_scaffold.324.32431717638912PgANHV/0.fa  -out .331.0.fa.pilecr.tmp -noinfo returned non-zero code 139
check out .331.0.fa.pilecr.tmp
[2019-10-21 12:10:59] INFO [job Execute_CRISPR_wnode] Max memory used: 36MiB
[2019-10-21 12:10:59] WARNING [job Execute_CRISPR_wnode] completed permanentFail
[2019-10-21 12:10:59] WARNING [step Execute_CRISPR_wnode] completed permanentFail
[2019-10-21 12:10:59] INFO [workflow bacterial_mobile_elem] completed permanentFail
[2019-10-21 12:10:59] WARNING [step bacterial_mobile_elem] completed permanentFail
[2019-10-21 12:10:59] INFO [workflow standard_pgap] completed permanentFail
[2019-10-21 12:10:59] WARNING [step standard_pgap] completed permanentFail
[2019-10-21 12:10:59] INFO [workflow ] completed permanentFail
```
And here is the end of the `ncbi_crisper_wnode.0.log` file:
```
wnode extra         id=lcl|NZ_JNMI01000006.1&id_offset=0
00324/004/0006/R  320D0144DADA04E1 0028/0006 2019-10-21T12:10:57.022212 a89a6049184f    UNK_CLIENT      UNK_SESSION              ncbi_crisper_wnode Error: NCBI_CRISPER "ncbi_crisper_wnode.cpp", line 393: ncbi::CGPX_NcbiCrisperJob::Process() --- Error in the body of Process: (CException::eUnknown) ncbi_crisper call failed: /opt/crispr/1.0/bin//ncbi_crisper /tmp/tmpn15i4az6/ncbi_crisper_wnode.324.324120404883200QhQlm/fasta_by_scaffold.324.32431717638912PgANHV/0.fa
00324/004/0006/R  320D0144DADA04E1 0029/0007 2019-10-21T12:10:57.022578 a89a6049184f    UNK_CLIENT      UNK_SESSION              ncbi_crisper_wnode Error: LIB "wn_worker_thread.cpp", line 275: ncbi::CWorkerThread::x_DoJob() --- error processing job: (CException::eUnknown) ncbi_crisper call failed: /opt/crispr/1.0/bin//ncbi_crisper /tmp/tmpn15i4az6/ncbi_crisper_wnode.324.324120404883200QhQlm/fasta_by_scaffold.324.32431717638912PgANHV/0.fa
00324/004/0006/RE 320D0144DADA04E1 0030/0008 2019-10-21T12:10:57.023659 a89a6049184f    UNK_CLIENT      UNK_SESSION              ncbi_crisper_wnode request-stop  500 0.447921991 0 0
00324/002/0007/RB 320D0144DADA04E1 0031/0001 2019-10-21T12:10:57.023831 a89a6049184f    UNK_CLIENT      UNK_SESSION              ncbi_crisper_wnode request-start internal_thread=output&processing_cycle=1&ncbi_app_version=0.0.0&ncbi_app_sc_version=22&ncbi_app_vcs_revision=591931
00324/002/0007/R  320D0144DADA04E1 0032/0002 2019-10-21T12:10:57.023862 a89a6049184f    UNK_CLIENT      UNK_SESSION              ncbi_crisper_wnode extra         success_jobs=0&fail_jobs=1
00324/002/0007/R  320D0144DADA04E1 0033/0003 2019-10-21T12:10:57.024068 a89a6049184f    UNK_CLIENT      UNK_SESSION              ncbi_crisper_wnode extra         attempts=1
00324/002/0007/RE 320D0144DADA04E1 0034/0004 2019-10-21T12:10:57.024119 a89a6049184f    UNK_CLIENT      UNK_SESSION              ncbi_crisper_wnode request-stop  200 0.000287771 0 0
00324/000/0000/P  320D0144DADA04E1 0035/0015 2019-10-21T12:10:59.573445 a89a6049184f    UNK_CLIENT      320D0144DADA04E1_0000SID ncbi_crisper_wnode Error: CORELIB(106.16) "ncbiapp.cpp", line 529: ncbi::CNcbiApplication::x_TryMain() --- Application's execution failed (CException::eUnknown) 1 jobs failed
00324/000/0000/PE 320D0144DADA04E1 0036/0016 2019-10-21T12:10:59.588016 a89a6049184f    UNK_CLIENT      320D0144DADA04E1_0000SID ncbi_crisper_wnode extra         ncbi_phid=320D0144DADA04E10000000000000001
00324/000/0000/PE 320D0144DADA04E1 0037/0017 2019-10-21T12:10:59.588113 a89a6049184f    UNK_CLIENT      320D0144DADA04E1_0000SID ncbi_crisper_wnode stop          3 4.776411056
```

Could you please help me to identify the problem?

**Comment by azat-badretdin** [comment]
Unfortunately this happens from time to time with pilercr (excellent third party product developed by Bob Edgar). Usually it indicates to some kind of low-complexity in input sequence. NNNN regions, for example.

**Comment by azat-badretdin** [comment]
>Can repeats cause such a problem?

Theoretically, yes. (I know, it's ironic, given that pilercr's main job is to find them :-) ). 

How long are repeats? If they are of 30-bases length then these are the CRISPR repeats and that's expected. Do you have repeats of other nature? What is the typical length and periodicity of these?

**Comment by liubovch** [comment]
There are att sites on both ends of the sequence, around 100 bases. There might be some duplicated genes, but this is all typical to bacterial genomes.

I expect there are no CRISPR regions in my sequence. It would be better maybe to have an option to skip some steps in the pipeline.

**Comment by azat-badretdin** [comment]
At this point I cannot investigate further without an input sequence. If the sequence is not covered by professional confidentiality feel free to post it and I will open an internal JIRA ticket to investigate what went wrong with pilercr.

**Comment by flandrs** [comment]
I got the same error  by using the freshly installed
PGAP version 2019-10-31.build4124
during the post-installation tests using the **mg37 test genome** :
./pgap.py -r -d -o mg37_results test_genomes/MG37/input.yaml
Stops with :
00366/000/0000/P  6D68016EDC4013F1 0006/0006 2019-11-07T11:34:25.069372 7aaf030a0593    UNK_CLIENT      6D68016EDC4013F1_0000SID ncbi_crisper_wnode Info: LIB "wn_app.cpp", line 273: ncbi::CGPX_WorkerApp::Run() --- output path: /pgap/output/debug/tmp-outdir/wrlfhjie/output
**=== STDOUT: /opt/crispr/1.0/bin//pilercr -in /tmp/tmpa46jziik/ncbi_crisper_wnode.366.36613733824320zPxXEb/fasta_by_scaffold.366.366333922270729ILfU6/0.fa  -out .373.0.fa.pilecr.tmp -noinfo
FATAL: /opt/crispr/1.0/bin//pilercr -in** /tmp/tmpa46jziik/ncbi_crisper_wnode.366.36613733824320zPxXEb/fasta_by_scaffold.366.366333922270729ILfU6/0.fa  -out .373.0.fa.pilecr.tmp -noinfo returned non-zero code 139
check out .373.0.fa.pilecr.tmp
This is greatly unexpected because I run this on another machine (and another version) without error

What have I to do ? Thanks

**Comment by slottad** [comment]
Sorry for your trouble @flandrs. `pilecr` is a third party app which we did not write. We are looking in to what could have caused this, but we are a bit flummoxed as we have not seen this problem using the test genome on any other machine.

**Comment by flandrs** [comment]
I have done two attempts (and a complete reinstall between :) )

**Comment by azat-badretdin** [comment]
As @slottad said this is a third party software and we can't do much about it.

**Comment by pvstodghill** [comment]
Sorry to post on a closed issue, but I think that I have some info that will be helpful to both users and the developers. I recently encountered the same failure with `pilercr` that others have when trying to annotate the test genome. In my case, the failure is caused by the fact the some component of pilercr` was compiled on an older Linux distribution and is being run on a more recent Linux distribution.

Look for the following message in the syslog (or dmesg):

```
[1047445.926201] pilercr[4985] vsyscall attempted with vsyscall=none ip:ffffffffff600400 cs:33 sp:7ffcca8b0ca8 ax:ffffffffff600400 si:710a60 di:0
```

`vsyscall` has been obsolete for awhile, but older toolchains, even currently supported versions of Centos still generate code that uses it. Recent versions of Debian (from Stretch on I believe) have disabled the use of `vsyscall` for security reasons. Recent versions of Ubuntu have _re-enabled_ `vsyscall` support for compatibility reasons. :-/

And this is the part that really stinks: Running the compiled code natively, under Docker, under Singularity, etc., makes no difference; if the host OS doesn't support `vsyscall`, then the code will fail.

Here are the steps to reproduce the problem:

1. Setup a machine with Debian Buster (10.x). I think that a VM machine will work, but I have only tested this on real hardware.
2. 

```
curl -OL https://github.com/ncbi/pgap/raw/prod/scripts/pgap.py
./pgap.py --update
./pgap.py -r -o mg37_results test_genomes/MG37/input.yaml
```

Here are some work-arounds for users:

1. Rebuild your machine with Centos or Ubuntu(?) :-(
2. Add `vsyscall=emulate` to your kernel parameters and reboot. WARNING: this does disable some small piece of the total security for your machine, so BEWARE.

Here is how the developers can fix the problem:

1. Recompile everything using a more recent toolchain.

Admittedly, I have not tested this solution...

HTH.
