### ISSUE TITLE
running time comparing with Prokka

### ISSUE THREAD

**Issue by wangdi2014** [ncbi/pgap#45]
Hello,

I am wondering why PGAP pipeline need so much time about 2.5 to 3 hours for one bacterial genome to complete compare with Prokka (mins for hundreds genomes)? What are the steps in PGAP taking it such long time?

Thanks!

**Comment by tseemann** [comment]
@wangdi2014  prokka author here. Prokka is designed to be fast, and it gets that by using lots of threads and parallel BLAST, but also my taking lots of shortcuts and using small databases.

PGAP is much more thorough, and gives better annotations. yes it's true :-).   Part of its slower speed comes from using CWL which can only run one process at a time, although BLAST within it uses multiple threads. The other reason is due to the 40 GB of databases it uses to ensure you get the best quality annotation possible. This also means you can submit it directly to Genbank/Refseq too.

They are really for different use-cases.  I am planning to improve accuracy of Prokka soon, and PGAP will get faster over time too.

**Comment by wangdi2014** [comment]
@tseemann Thanks very much for your explanation!

**Comment by abrozzi** [comment]
I do confirm the point raised by @wangdi2014.
I made a test with 8 CPUS and 33 GB of memory:

`-s 'Escherichia coli' -c 8 -m 32BG` for a genome of E coli. 

It took 1 hour and 15 minutes. At the end it retrieved ca 5000 protein sequences which is in line with the expectations for that species.

HTH
