### ISSUE TITLE
input-2020-02-06.build4373.tgz not found at: https://s3.amazonaws.com/pgap-data/

### ISSUE THREAD

**Issue by dbayles** [ncbi/pgap#57]
Updating PGAP to 2020-02-06.build4373 failed.  The input database cannot be retrieved from: https://s3.amazonaws.com/pgap/input-2020-02-06.build4373.tgz.  Note: test_genomes-2020-02-06.build4373.tgz is found.

Darrell

**Comment by azat-badretdin** [comment]
Thanks for reporting, Darrell! Someone will have a look at earliest opportunity

**Comment by slottad** [comment]
Sorry about that. I've corrected the problem, and you may try again.

The problem is we changed the file naming scheme in a way that broke the old version of pgap.py. I have changed it back in order not to break to program  for those who are using  old copies of pgap.py. However, to use the new features, you should update your copy via the instructions on the Quick-Start page.

The new copy of pgap.py will auto-update so this should not occur again.

**Comment by dbayles** [comment]
Thanks!
