### ISSUE TITLE
[FEATURE REQUEST] Add dockerfile to repo?

### ISSUE THREAD

**Issue by kapsakcj** [ncbi/pgap#61]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Add the dockerfile for `ncbi/pgap` (maybe `ncbi/pgap-utils` too?) to this github repository.

**Describe alternatives you've considered**
None.

**Additional context**
I've found it incredibly useful to link github repositories that contain dockerfiles and respective dockerhub repositories for building docker images. You can set up dockerhub to automatically build the image if you push a commit to the master branch or turn off the autobuild feature so that builds must be manually triggered (perhaps for each software release or similar milestone).

I appreciate everyone's efforts for putting together this wonderful tool and for creating the docker image. This will greatly increase portability and allow more folks to run PGAP without having to struggle too much with the install. Hosting the dockerfile on this repo will really help iron out bugs with the rollout of Singulary/podman/etc. support.

Thanks!
Curtis

**Comment by slottad** [comment]
The problem with our docker file is that it can only really be built at NCBI because it depends upon so many internal resources. It is the reason that we are using docker in the first place, otherwise it would have been well neigh impossible to compile and run this elsewhere.

Because it references all these resources, our security folks are reluctant to have it public, and this is not a fight that will be helped by having reason and facts on our side.

**Comment by kapsakcj** [comment]
> this is not a fight that will be helped by having reason and facts on our side.

An all too familiar situation for those working for the government O___O

Thanks for the quick response.
