### ISSUE TITLE
[BUG] PGAP crashes during cluster_blastp_wnode

### ISSUE THREAD

**Issue by MrTomRod** [ncbi/pgap#76]
PGAP dies during the annotation of this genome assembly: [GenBank VBSP00000000](https://www.ncbi.nlm.nih.gov/nuccore/VBSP00000000).

My PGAP installation works well on other assemblies I tried to annotate.

Luckily, since the genome has been published, I can provide all logs [here](https://cloud.roder.casa/s/xLRQqAg3cnErNrM).

Sneakpeak from `cwltoolt.log`:

```
21051/000/0000/P  A914523BEC3897A1 0007/0007 2020-05-19T07:23:38.499812 119d93f36c30    UNK_CLIENT      UNK_SESSION              cluster_blastp_wnode Info: LIB "wn_app.cpp", line 273: ncbi::CGPX_WorkerApp::Run() --- output path: /pgap/output/debug/tmp-outdir/s5t48x0l/output
[2020-05-19 09:58:04] INFO [job cluster_blastp_wnode] Max memory used: 23MiB
[2020-05-19 09:58:08] WARNING [job cluster_blastp_wnode] completed permanentFail
[2020-05-19 09:58:08] WARNING [step cluster_blastp_wnode] completed permanentFail
[2020-05-19 09:58:08] INFO [workflow cluster_and_qdump] completed permanentFail
[2020-05-19 09:58:08] WARNING [step cluster_and_qdump] completed permanentFail
[2020-05-19 09:58:08] INFO [workflow Find_Naming_Protein_Hits_I] completed permanentFail
[2020-05-19 09:58:08] WARNING [step Find_Naming_Protein_Hits_I] completed permanentFail
[2020-05-19 09:58:09] INFO [workflow bacterial_annot_2] completed permanentFail
[2020-05-19 09:58:09] WARNING [step bacterial_annot_2] completed permanentFail
[2020-05-19 09:58:09] INFO [workflow standard_pgap] completed permanentFail
[2020-05-19 09:58:09] WARNING [step standard_pgap] completed permanentFail
[2020-05-19 09:58:09] INFO [workflow ] completed permanentFail
{
...
}
[2020-05-19 09:58:12] WARNING Final process status is permanentFail
```

**Comment by azat-badretdin** [comment]
Could you please post?


**Software versions (please complete the following information):**
 - OS: [e.g. CentOS 7, Windows 10, etc.]
 - pgap.py --version, or docker image version.
 - Docker (or other container runner) version. [e.g. ``docker --version``]

**Comment by MrTomRod** [comment]
```
$ ./pgap.py --version
PGAP version 2020-03-30.build4489 is up to date.
$ docker --version
Docker version 19.03.9, build 9d988398e7
$ uname -r
3.10.0-1062.12.1.el7.x86_64
$ cat /etc/system-release
CentOS Linux release 7.8.2003 (Core)
```

**Comment by azat-badretdin** [comment]
Thanks What's your memory and what is memory allocated to docker?

**Comment by MrTomRod** [comment]
```
$ free -h
              total        used        free      shared  buff/cache   available
Mem:            62G         25G        340M        5.5M         36G         36G
Swap:          1.0G        333M        684M
```
This is what I get when I run `docker stats <container-id>` on a currently running container that was started in the same way:
```
CONTAINER ID        NAME                CPU %               MEM USAGE / LIMIT     MEM %               NET I/O             BLOCK I/O           PIDS
59d0ed04aa74        thirsty_liskov      117.91%             171.6MiB / 62.76GiB   0.27%               656B / 0B           0B / 0B             13
```

Hope that helps...?

**Comment by azat-badretdin** [comment]
Thanks! We will look at this data

**Comment by azat-badretdin** [comment]
Looks like genome is quite small: ~2571361 bytes (FASTA file I downloaded for this assembly)

**Comment by azat-badretdin** [comment]
Quite enigmatic. I examined `debug/` output for the node, seems fine: no errors in the log for the app, no bad job-statuses for the output/ directory. 

Were you able to successfully annotate anything else with this particular release (or previous releases of PGAPX)?

**Comment by MrTomRod** [comment]
I downloaded the assembly here: https://www.ncbi.nlm.nih.gov/assembly/GCF_005864045.1

The file I tried to annotate contains the same sequence as the one that was already successfully annotated by NCBI's PGAP.

**Comment by MrTomRod** [comment]
> Were you able to successfully annotate anything else with this particular release (or previous releases of PGAPX)?

I used this particular version on tens of genomes.

**Comment by azat-badretdin** [comment]
I will run it myself then on our cloud pet.

**Comment by MrTomRod** [comment]
Meanwhile, I got a similar problem with this assembly: [GCF_005890155.1](https://www.ncbi.nlm.nih.gov/assembly/GCF_005890155.1/). 

The assembly consists of a single, circular scaffold. This time, you can't make fun of the size (or shape) of my genome. ;)

PGAP produced 12 GB of debugging-logs, which I compressed and uploaded [here](https://cloud.roder.casa/s/Jicz2QnSpCLYJs6). Maybe, it helps find the problem.

**Comment by whlavina** [comment]
Logs suggest a process crash, and did indicate memory may be tight. I suggest trying `--cpus 8`, reducing by half the memory pressure. If that works, please let us know so we can confirm the issue, in which case we'll look at improving logs and diagnostics.

This is how I am diagnosing the issue:
- In `cwltool.log`, there was a `permanentFail` for `cluster_blastp_wnode_2`. The log line preceding this, gave an output path to inspect: `output path: /pgap/output/debug/tmp-outdir/bpoz4zb3/output`
- In `debug/tmp-outdir/bpoz4zb3/ncbiapp.log`, there is no error message in this machine-parseable log format, but it is supposed to end with a line that says `app stop` on completion; absence of such log line, suggests the process crashed. This log ends with `pct_ram_used=67`, but there are earlier logs with `pct_ram_used` significantly above 100%, which suggests memory exhaustion and use of swap.

Memory requirements for this multi-threaded application, are variable due to concurrency, and it's possible that peak memory usage is affected by bad luck if multiple large jobs just happen to co-occur.

**Comment by azat-badretdin** [comment]
>This time, you can't make fun of the size (or shape) of my genome. ;)

**Comment by MrTomRod** [comment]
Thanks for the information... I'm trying again with only 8 cores. At the same time, I'll be logging docker stats with this "elegant" command:

`while true; do docker stats --no-stream | tee --append stats.txt; sleep 10; done`

**Comment by azat-badretdin** [comment]
Let's define elegant (without quotes) every BASH oneliner by definition :-)

**Comment by MrTomRod** [comment]
It worked with 8 cores and 60GB RAM. These are the stats for the second assembly (GCF_005890155.1):

![image](https://user-images.githubusercontent.com/40867365/82675353-ff1cad00-9c44-11ea-9e6a-ca88e7c1562e.png)

(Logs start a few minutes after I started the container.)

**Comment by azat-badretdin** [comment]
Thanks! The patter of green is consistent with double call to cluster_blastp_wnode - our beloved CPU-churning elephant - first one is longer, because it chews through about 60K ORFs, the second one is only realistic protein candidates (~5000). The blue line increase is within that second call, so I am guessing cluster_blastp_wnode demands this amount of memory for something that BLAST does.
