### ISSUE TITLE
Flushed output for job and [job cluster_blastp_wnode_2] completed permanentFail

### ISSUE THREAD

**Issue by HJuan412** [ncbi/pgap#89]
After successfully annotating the MG37 genome, I've been trying to use pgap on an assembly of my own. The program does well until cluster_blastp_wnode_2:

> [2020-07-25 21:41:52] INFO [job cluster_blastp_wnode_2] Max memory used: 2426MiB
[2020-07-25 21:41:52] WARNING [job cluster_blastp_wnode_2] completed permanentFail
[2020-07-25 21:41:52] WARNING [step cluster_blastp_wnode_2] completed permanentFail
[2020-07-25 21:41:52] INFO [workflow cluster_and_qdump_2] completed permanentFail
[2020-07-25 21:41:52] WARNING [step cluster_and_qdump_2] completed permanentFail
[2020-07-25 21:41:52] INFO [workflow Find_Naming_Protein_Hits] completed permanentFail
[2020-07-25 21:41:52] WARNING [step Find_Naming_Protein_Hits] completed permanentFail
[2020-07-25 21:41:52] INFO [workflow bacterial_annot_4] completed permanentFail
[2020-07-25 21:41:52] WARNING [step bacterial_annot_4] completed permanentFail
[2020-07-25 21:41:52] INFO [workflow standard_pgap] completed permanentFail
[2020-07-25 21:41:52] WARNING [step standard_pgap] completed permanentFail
[2020-07-25 21:41:52] INFO [workflow ] completed permanentFail
{
    ...
}
[2020-07-25 21:41:52] WARNING Final process status is permanentFail

prior to this, there's a string of 166 error lines:

> Error: Flushed output for job 73, file on disk /pgap/output/debug/tmp-outdir/bgispzrr/output/efd8a5dd4651.20200725195834.10887.18 length 114152, timestamp 07/25/2020 20:30:11

looking into the debug/tmp-outdir/bgispzrr/output/ncbiapp.log file I found they look like:
> 10887/006/1772/R  DD992A87F1C8EEA1 8342/0131 2020-07-25T21:13:16.382637 efd8a5dd4651    UNK_CLIENT      UNK_SESSION              cluster_blastp_wnode Error: LIB "wn_worker_thread.cpp", line 394: ncbi::CWorkerThread::x_Flush() --- Flushed output for job 169, file on disk /pgap/output/debug/tmp-outdir/bgispzrr/output/efd8a5dd4651.20200725195834.10887.6 length 357514, timestamp 07/25/2020 21:13:16

This is the command I've been using:

> sudo nohup ./pgap.py -o <mypreix> -r --taxcheck --debug -c 10 -m 40g input.yaml

**Software versions:**
- OS: VERSION="18.04.4 LTS (Bionic Beaver)" 
- PGAP version 2020-07-09.build4716 is up to date.
- Docker version 19.03.12, build 48a66213fe

free -h

>               total        used        free      shared  buff/cache   available
>               Mem:            62G        560M         40G        1,3M         21G         61G
>               Swap:          2,0G        1,9M        2,0G

**Log Files**
[cwltool.log](https://github.com/ncbi/pgap/files/4977840/cwltool.log)

**Comment by whlavina** [comment]
Please ignore the "Flushed" messages. They are temporary debugging logs, emitted at Error severity as a convenience for our analysis; this temporary logging should have been removed before public release.

The most likely cause of the failure is insufficient memory. We specify, in our Requirements:
> 2GB-4GB of memory available per CPU used by your container.

Your host appears to meet this requirement, but:
- you are specifying a memory limit via `-m 40g` which is lower than our recommended minimum, given you have 16 cores;
- the memory requirements are an approximation, and given that processing involves concurrency, it's possible that actual memory requirements may spike and vary somewhat from run to run.

Please try again, increasing or removing the `-m 40g` option if you can, as was shown from the log:
```
Original command: ./pgap.py -o PSBLACK -r --taxcheck --debug -c 10 -m 40g pseudomonas/input.yaml
[...]
    "CPU cores": 16,
    "memory (GiB)": 62.8,
    "memory per CPU core (GiB)": 3.9,
```

If you cannot increase the memory, you may try decreasing the parallelism via `--cpu`, but due to our open Issue #77, that probably won't work at this time.

If you have access to other host configurations with more memory per CPU (whether increasing the memory or decreasing the CPU count), please try that.

Finally, If the problem persists, we will need additional log files to diagnose.
Please run with the `--debug` option, and attach an archive (e.g. zip or tarball) of the logs in: `debug/tmp-outdir/*/*.log`

**Comment by HJuan412** [comment]
Raising the memory limit to 64 gb did it. I'd assumed 4 gb per process would be fine, hadn't accounted for variation
