### ISSUE TITLE
[BUG] <title>MUST WE NECESSARILY HAVE A COMPUTER CLUSTER TO RUN PGAP

### ISSUE THREAD

**Issue by gilmahu** [ncbi/pgap#98]
Dear GPAP Developers and every user out there, 

I have had some very useful guidance from Azat and others the past weeks when trying to run PGAP on my personal mac but it failed. The issue was memory-related. 
I am using a MacBook pro of 8 CPU and 16GB Ram. 
I was also advised to fix the memory requirements in my docker preferences which I did and it seemed fine but at the end of the day the annotation of a 4MB Vibrio cholerae genome never completed and as suggested by Azat it was insufficient memory thing.  
So I would like to ask if anyone out there had tried to run PGAP with a personal computer of this kind of memory size and what would you advise me from your experience. 
Or PGAP built only to run on large computer clusters? 
Is there any extra solution for me besides looking for a could computer which I currently have no access to?  
in the YouTube NCBI minute on PGAP it was said that a 1 CPU for 12 GB memory was sufficient (https://www.youtube.com/watch?v=pNn_-_46lpI)

Best regards 
Gildas

**Comment by azat-badretdin** [comment]
At this point the word "cluster" is a red herring. Individual runs of pgap.py are always within one closed system. In this sense pgap.py is designed to run in "anti-cluster" environment. 

"Cluster", or, better, "cloud" computing comes here as just one of convenient ways of quickly renting a machine with necessary requirements without a burden of ordering and maintaining "own" computer. 

We have been always committed to providing users an ability to run PGAP on personal computers, but we also, from the very beginning have to deal with hefty system requirements  that were on the upper end edge of personal computers. 

With time requirements tend to grow because the reference data tends to grow and the processes that use that reference data become more memory-hungry. 

On the youtube video. The information you have access on the web becomes dated with time because things change. 

We are actively working on minimizing CPU footprint of PGAP.

**Comment by gilmahu** [comment]
So this technically means that right now there are not any options for me to successfully use PGAP with my current computer?

**Comment by azat-badretdin** [comment]
The option are: "rent" a cloud computer (this could be arranged via your systems in your organization), access a larger computer from your organization.  Basically, talk to systems in your organization, maybe they can help with computing resources. 

Maybe other members of our team have better suggestions on how to utilize your own personal computer.

**Comment by whlavina** [comment]
You say you have a Mac with 16 GB. On issue #66, I believe you configured Docker (via Preferences), to 4 CPU and 8 GB.
Can you reduce the CPU setting and increase the memory setting?
Say, 3 CPU and 15 GB?

**Comment by gilmahu** [comment]
@whlavina I tried 3 CPU for 15 GB and it failed but 2 CPU for 15GB completed successfully a 4MB assembly after about 12hrs. 
Thanks!
